# Generated by Django 5.2.4 on 2025-07-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='area_tecnica/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
